//! # forcefield
//!
//! A hand port of [d3-force](https://github.com/d3/d3-force) 2.1.1 (whose
//! source is byte-identical to 3.0.0) and the d3-quadtree Barnes-Hut
//! structure it depends on. Pure `f64` math, no I/O, no timers: you own the
//! tick loop.
//!
//! The port preserves floating-point operation order and traversal order,
//! and reproduces d3's `lcg` random source, so a simulation here produces
//! the same positions, bit for bit, as the JS reference on every tick. The
//! `parity/` harness in the repository checks that against golden frames
//! generated by d3-force itself.
//!
//! ```
//! use forcefield::{Simulation, Node, forces::{ManyBody, Link, Center}};
//!
//! let mut sim = Simulation::with_count(3);
//! sim.add_force("charge", Box::new(ManyBody::new()))
//!    .add_force("link", Box::new(Link::new(vec![(0, 1), (1, 2)])))
//!    .add_force("center", Box::new(Center::new(0.0, 0.0)));
//! sim.tick(10);
//! let b = sim.bodies();
//! assert!(b.x(0).is_finite());
//! ```

pub mod bodies;
pub mod forces;
pub mod lcg;
pub mod quadtree;
pub mod simulation;

pub use bodies::{Bodies, Node};
pub use forces::Force;
pub use lcg::{Lcg, Random};
pub use simulation::Simulation;
